import torch
import torch.nn as nn
from typing import Dict, Optional, List
from pathlib import Path
from hydra.core.hydra_config import HydraConfig
import logging

logger = logging.getLogger(__name__)

class SequentialTrainer:
    def __init__(
        self, 
        model, 
        optimizer, 
        strategy,
        device, 
        metrics=None,
        max_epochs_per_task=3, 
        log_interval=100,
    ):
        # Keep a reference to the unwrapped model for strategy hooks and checkpointing.
        # DataParallel wraps the model, but strategies and save_model always need raw weights.
        self._raw_model = model
        self.optimizer = optimizer
        self.strategy = strategy
        self.device = device
        self.metrics = metrics
        self.max_epochs_per_task = max_epochs_per_task
        self.log_interval = log_interval
        self.criterion = nn.CrossEntropyLoss()
        self.num_tasks = None

        # Wrap with DataParallel when multiple CUDA GPUs are available.
        # NOTE 1: for small models (MLP) this rarely helps due to scatter/gather overhead.
        #       It pays off for ResNet+ with large batch sizes.
        # DISCLAIMER: The DataParallel logic was fully generated by GenAI (GitHub Copilot) 
        num_gpus = torch.cuda.device_count()
        if num_gpus > 1:
            logger.info(f"Using DataParallel across {num_gpus} GPUs.")
            self.model = nn.DataParallel(model)
        else:
            self.model = model


        
    def train_one_epoch(self, task_id: str, train_loader):
        """Train for one epoch.
        
        Args:
            task_id: Current task identifier
            train_loader: DataLoader for this epoch
        """
        self.model.train()
        running_loss = 0.0
        correct = 0
        total = 0
        
        for batch_idx, (images, targets) in enumerate(train_loader):
            images = images.to(self.device)
            targets = targets.to(self.device)
            
            self.optimizer.zero_grad()
            outputs = self.model(images)
            # Use strategy to compute loss (pass unwrapped model for parameter access)
            loss = self.strategy.compute_loss(self._raw_model, images, outputs, targets, task_id)
            loss.backward()
            self.strategy.after_backward(self._raw_model, task_id)
            self.optimizer.step()
            
            running_loss += loss.item() * images.size(0)
            _, preds = outputs.max(1)
            correct += (preds == targets).sum().item()
            total += targets.size(0)
            
            if (batch_idx + 1) % self.log_interval == 0:
                logger.info(f'    Batch {batch_idx + 1}: loss={loss.item():.4f}')
                
        return running_loss / total, correct / total
    
    def evaluate(self, test_loader):
        """Evaluate on test set."""
        self.model.eval()
        running_loss = 0.0
        correct = 0
        total = 0
        
        with torch.no_grad():
            for images, targets in test_loader:
                images = images.to(self.device)
                targets = targets.to(self.device)
                
                outputs = self.model(images)
                loss = self.criterion(outputs, targets)
                
                running_loss += loss.item() * images.size(0)
                _, preds = outputs.max(1)
                correct += (preds == targets).sum().item()
                total += targets.size(0)
                
        return running_loss / total, correct / total
    
    def evaluate_on_all_tasks(self, test_loaders: Dict):
        """Evaluate on all tasks after training on one task.
        
        Fills a complete row of Matrix R: runs evaluation on all test sets
        after training on the current task, and records results in metrics.
        This matrix is later used for BWT and ACC computation and could be
        used for further metrics (e.g. FWT) in the future.
        
        Args:
            test_loaders: Dictionary mapping task_id -> test DataLoader
        """
        if self.metrics is None:
            return
        
        logger.info(f"\nEvaluating on all tasks:")
        logger.info("-" * 60)
        for test_task, test_loader in test_loaders.items():
            loss, accuracy = self.evaluate(test_loader)
            # Store in metrics using the pre-computed accuracy value
            self.metrics.record_accuracy_value(test_task, accuracy)
            logger.info(f"  Task {test_task}: loss={loss:.4f}, accuracy={accuracy:.4f}")
        logger.info("")

    def train_task(self, task: str, train_loader, test_loaders: Dict):
        """Train on one task and evaluate on all tasks.
        
        Args:
            task: Task identifier
            train_loader: Training DataLoader
            test_loaders: Dictionary mapping task_id -> test DataLoader
        """
        # Initialize metrics for this task
        if self.metrics is not None:
            self.metrics.reset(task)
        
        # Call strategy hook before task (always pass the unwrapped model)
        self.strategy.before_task(self._raw_model, task, self.num_tasks)
        
        logger.info(f"\n{'='*60}")
        logger.info(f"TASK {task} - Training")
        logger.info(f"{'='*60}\n")
        
        for epoch in range(1, self.max_epochs_per_task + 1):
            logger.info(f'Epoch {epoch}/{self.max_epochs_per_task}')
            
            # Train on current task
            train_loss, train_acc = self.train_one_epoch(task, train_loader)
            logger.info(f'  Train: loss={train_loss:.4f}, acc={train_acc:.4f}')
            
            # Evaluate on current task
            test_loss, test_acc = self.evaluate(test_loaders[task])
            logger.info(f'  Test:  loss={test_loss:.4f}, acc={test_acc:.4f}')
        
        # Call strategy hook after task (always pass the unwrapped model)
        self.strategy.after_task(self._raw_model, task, train_loader)
        
        # Evaluate on all tasks to fill one row of Matrix R
        self.evaluate_on_all_tasks(test_loaders)
    
    def fit(self, datamodule, tasks: Optional[List[str]] = None):
        """Train through all tasks sequentially."""
        if tasks is None:
            tasks = ['A', 'B', 'C']
        self.num_tasks = len(tasks)

        test_loaders = {task: datamodule.get_test_loader(task) for task in tasks}
        
        for task in tasks:
            train_loader = datamodule.get_train_loader(task)
            self.train_task(task, train_loader, test_loaders)
            # Save after each task
            self.save_model(f"model_task_{task}.pth")
        
        # Save final model
        self.save_model("model_final.pth")
        
        # Print and save metrics
        if self.metrics is not None:
            self.metrics.print_summary()
            # Save metrics to Hydra run folder
            hydra_cfg = HydraConfig.get()
            metrics_path = Path(hydra_cfg.run.dir) / 'metrics.json'
            self.metrics.save(str(metrics_path))
        
    def save_model(self, filename: str = "model.pth"):
        """Save checkpoint to Hydra run folder."""
        hydra_cfg = HydraConfig.get()
        run_dir = Path(hydra_cfg.run.dir)
        models_dir = run_dir / 'models'
        models_dir.mkdir(parents=True, exist_ok=True)
        out_path = models_dir / filename
        checkpoint = {
            'model_state_dict': self._raw_model.state_dict(),  # never the DataParallel wrapper
            'optimizer_state_dict': self.optimizer.state_dict()
        }
        torch.save(checkpoint, out_path)
        logger.info(f"Saved model checkpoint to {out_path}")